import { useState } from 'react'
import { Link } from 'react-router-dom'
import Navbar from '../components/Navbar'

const SECTIONS = [
  {
    title: 'Products & Orders',
    items: [
      {
        q: 'What makes Nordic Vitals supplements different?',
        a: 'Our products are sourced from certified Nordic suppliers using cold-extraction and minimal processing. Each batch is third-party tested for purity and potency. We never use synthetic fillers or artificial colours.',
      },
      {
        q: 'How long does shipping take?',
        a: 'Standard delivery within Norway takes 2–4 business days. European orders typically arrive in 5–9 business days. We offer free shipping on all orders — no minimum required.',
      },
      {
        q: 'Can I return or exchange a product?',
        a: 'Yes. We offer a 30-day satisfaction guarantee. If you are not happy with your order for any reason, contact us within 30 days of delivery for a full refund or exchange. Return shipping is covered for defective or incorrectly shipped items.',
      },
      {
        q: 'How do I track my order?',
        a: 'Once your order ships you will receive a tracking number by email. You can also view all your orders under My Orders in your member dashboard.',
      },
      {
        q: 'Are your products suitable for vegans?',
        a: 'Most of our products are vegan-friendly. Each product page clearly lists the full ingredient list and allergen information. Our Omega-3 range is derived from algae, making it suitable for vegans.',
      },
      {
        q: 'Can I buy without becoming a member?',
        a: 'Absolutely. You can shop at standard retail prices without any membership. Members receive a discounted member price on every product.',
      },
    ],
  },
  {
    title: 'Membership & MLM',
    items: [
      {
        q: 'What does it mean to become a member?',
        a: 'Nordic Vitals membership gives you access to member pricing, a personal referral link, and the ability to earn commissions when you refer others who purchase or join. There is no mandatory monthly purchase to stay active.',
      },
      {
        q: 'Is there a cost to join?',
        a: 'Joining is free. You simply create an account. An optional Starter Pack is available if you want to begin with a curated product bundle and earn a higher PV credit.',
      },
      {
        q: 'How do commissions work?',
        a: 'You earn Direct Referral commissions when someone you recruit makes a purchase. Depending on your rank, you also earn Matching and Override bonuses from your wider downline. All commissions are calculated in MLMT tokens and can be withdrawn once per period.',
      },
      {
        q: 'What is MLMT?',
        a: 'MLMT (MultiLevel Member Token) is the internal reward token used across the Arctico MLM platform. Your earned MLMT can be withdrawn to a supported wallet or used to offset future purchases.',
      },
      {
        q: 'What are PV and BV?',
        a: 'PV (Personal Volume) is the volume credit generated by your own purchases. BV (Business Volume) is the volume generated by your wider organisation. Both are used to calculate your rank and commission eligibility each period.',
      },
      {
        q: 'How do I advance in rank?',
        a: 'Each rank requires a combination of personal volume (PV), organisation volume (BV), and a minimum number of active downline members. Your current rank progress is visible on the Earnings page of your dashboard.',
      },
      {
        q: 'Is this a pyramid scheme?',
        a: 'No. Nordic Vitals is a legitimate direct-sales company where commissions are earned on actual product sales, not on recruitment fees alone. You are never required to recruit anyone to earn your member discount or to buy products.',
      },
    ],
  },
  {
    title: 'Account & Technical',
    items: [
      {
        q: 'I forgot my password. What should I do?',
        a: 'Click "Forgot password?" on the login page and enter your email address. You will receive a reset link within a few minutes. Check your spam folder if it does not arrive.',
      },
      {
        q: 'How do I update my profile or email address?',
        a: 'Go to My Profile in your member dashboard. You can update your name, phone number, and country there. For email changes please contact support as this requires identity verification.',
      },
      {
        q: 'I am not receiving emails from Nordic Vitals.',
        a: 'Please check your spam or junk folder and whitelist support@nordic-vitals.com. If you still have issues, contact us and we can verify your registered email address.',
      },
      {
        q: 'Is my payment information secure?',
        a: 'Yes. We do not store card numbers. All payments are processed via PCI-DSS certified payment providers. Your personal data is handled in accordance with GDPR — see our Privacy Policy for details.',
      },
    ],
  },
]

function Accordion({ q, a }) {
  const [open, setOpen] = useState(false)
  return (
    <div style={{
      borderBottom: '1px solid var(--border)',
      padding: '0',
    }}>
      <button
        onClick={() => setOpen(v => !v)}
        style={{
          width: '100%', textAlign: 'left', background: 'none', border: 'none',
          padding: '18px 4px', display: 'flex', justifyContent: 'space-between',
          alignItems: 'flex-start', gap: '16px', cursor: 'pointer',
        }}
      >
        <span style={{ fontSize: '15px', fontWeight: 600, color: 'var(--cream)', flex: 1, lineHeight: 1.4 }}>{q}</span>
        <span style={{
          color: 'var(--gold)', fontSize: '18px', lineHeight: 1, flexShrink: 0,
          transform: open ? 'rotate(45deg)' : 'none', transition: 'transform 0.2s',
        }}>+</span>
      </button>
      {open && (
        <div style={{ padding: '0 4px 18px', fontSize: '14px', color: 'var(--text2)', lineHeight: 1.7 }}>
          {a}
        </div>
      )}
    </div>
  )
}

export default function FAQPage() {
  return (
    <>
      <Navbar />
      <div style={{ minHeight: '100vh', background: 'var(--navy)', paddingTop: '72px' }}>
        {/* Hero */}
        <div style={{ background: 'var(--navy2)', borderBottom: '1px solid var(--border)', padding: '56px 24px 48px' }}>
          <div style={{ maxWidth: '760px', margin: '0 auto', textAlign: 'center' }}>
            <div style={{ fontSize: '12px', color: 'var(--gold)', fontWeight: 700, letterSpacing: '2px', textTransform: 'uppercase', marginBottom: '12px' }}>
              HELP CENTRE
            </div>
            <h1 style={{ fontSize: '36px', fontWeight: 800, color: 'var(--cream)', marginBottom: '14px', lineHeight: 1.15 }}>
              Frequently Asked Questions
            </h1>
            <p style={{ fontSize: '16px', color: 'var(--text2)', maxWidth: '520px', margin: '0 auto' }}>
              Everything you need to know about Nordic Vitals products, membership, and commissions.
            </p>
          </div>
        </div>

        {/* Content */}
        <div style={{ maxWidth: '760px', margin: '0 auto', padding: '56px 24px 80px' }}>
          {SECTIONS.map(section => (
            <div key={section.title} style={{ marginBottom: '48px' }}>
              <h2 style={{
                fontSize: '13px', fontWeight: 700, color: 'var(--gold)',
                textTransform: 'uppercase', letterSpacing: '1.5px',
                marginBottom: '8px',
              }}>
                {section.title}
              </h2>
              <div style={{
                background: 'var(--navy2)',
                border: '1px solid var(--border)',
                borderRadius: '12px',
                padding: '0 20px',
              }}>
                {section.items.map(item => (
                  <Accordion key={item.q} q={item.q} a={item.a} />
                ))}
              </div>
            </div>
          ))}

          {/* Still need help */}
          <div style={{
            textAlign: 'center',
            background: 'var(--navy2)',
            border: '1px solid var(--border)',
            borderRadius: '16px',
            padding: '40px 32px',
          }}>
            <div style={{ fontSize: '24px', marginBottom: '10px' }}>💬</div>
            <h3 style={{ fontSize: '18px', fontWeight: 700, color: 'var(--cream)', marginBottom: '8px' }}>
              Still have questions?
            </h3>
            <p style={{ fontSize: '14px', color: 'var(--text2)', marginBottom: '20px' }}>
              Our team is happy to help. We typically respond within one business day.
            </p>
            <Link to="/contact" className="btn btn-gold" style={{ fontSize: '14px' }}>
              Contact Support
            </Link>
          </div>
        </div>
      </div>
    </>
  )
}
